# Generated by Django 5.1.2 on 2024-11-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('herb', 'Herb'), ('tree', 'Tree'), ('vegetables', 'Vegetables'), ('frult', 'Frult'), ('flower', 'Flower')], default='tree', max_length=10),
        ),
    ]
